sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/points
    max_range: 4.0
    frame_subsample: 1
    point_subsample: 1
    shape_padding: 0.005
    shape_scale: 1.0
    filtered_cloud_topic: filtered_cloud
