controller_list:
  - name: j2s6s200/effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j2s6s200_joint_1
      - j2s6s200_joint_2
      - j2s6s200_joint_3
      - j2s6s200_joint_4
      - j2s6s200_joint_5
      - j2s6s200_joint_6
  - name: j2s6s200/effort_finger_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true    
    joints:
      - j2s6s200_joint_finger_1
      - j2s6s200_joint_finger_2
