arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin 
  #kinematics_solver: m1n6s200_mico_arm_kinematics/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
