j2n7s300:
  effort_finger_trajectory_controller:
    constraints:
      goal_time: 20.0
      j2n7s300_joint_finger_1:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_finger_2:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_finger_3:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02
    gains:
      j2n7s300_joint_finger_1:
        d: 0.0
        i: 0.01
        i_clamp: 1
        p: 10.0
      j2n7s300_joint_finger_2:
        d: 0.0
        i: 0.01
        i_clamp: 1
        p: 10.0
      j2n7s300_joint_finger_3:
        d: 0.0
        i: 0.01
        i_clamp: 1
        p: 10.0
    joints:
    - j2n7s300_joint_finger_1
    - j2n7s300_joint_finger_2
    - j2n7s300_joint_finger_3
    type: effort_controllers/JointTrajectoryController
  effort_joint_trajectory_controller:
    constraints:
      goal_time: 20.0
      j2n7s300_joint_1:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_2:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_3:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_4:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_5:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_6:
        goal: 0.02
        trajectory: 0.05
      j2n7s300_joint_7:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02
    gains:
      j2n7s300_joint_1:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
      j2n7s300_joint_2:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
      j2n7s300_joint_3:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
      j2n7s300_joint_4:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
      j2n7s300_joint_5:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
      j2n7s300_joint_6:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
      j2n7s300_joint_7:
        d: 2.0
        i: 0.01
        i_clamp: 1
        p: 1000.0
    joints:
    - j2n7s300_joint_1
    - j2n7s300_joint_2
    - j2n7s300_joint_3
    - j2n7s300_joint_4
    - j2n7s300_joint_5
    - j2n7s300_joint_6
    - j2n7s300_joint_7
    type: effort_controllers/JointTrajectoryController
  j2n7s300_joint_1_position_controller:
    joint: j2n7s300_joint_1
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_2_position_controller:
    joint: j2n7s300_joint_2
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_3_position_controller:
    joint: j2n7s300_joint_3
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_4_position_controller:
    joint: j2n7s300_joint_4
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_5_position_controller:
    joint: j2n7s300_joint_5
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_6_position_controller:
    joint: j2n7s300_joint_6
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_7_position_controller:
    joint: j2n7s300_joint_7
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_finger_1_position_controller:
    joint: j2n7s300_joint_finger_1
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_finger_2_position_controller:
    joint: j2n7s300_joint_finger_2
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  j2n7s300_joint_finger_3_position_controller:
    joint: j2n7s300_joint_finger_3
    pid:
      d: 10.0
      i: 0.01
      p: 1000.0
    type: effort_controllers/JointPositionController
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController
